export const burgers = [
    {id: "burger-arnor", name: "Arnor's Hamberder", desc: "Great Gondorian cuisine", price: "49.9k"},
    {id: "burger-rohan", name: "Rohan's Bacon Cheeseburger", desc: "16oz beef patty, bacon, cheese", price: "54.9k"},
    {id: "burger-gondor", name: "Gondorian Hot Sandwich", desc: "Arnor's Hamberder, gravy, topped with cheese", price: "54.9k"},
    {id: "burger-mordor", name: "Mordor Sizzler", desc: "Deep-fried chicken, lettuce, tomato, onion", price: "49.9k"},
    {id: "burger-hobbiton", name: "Hobbiton Special", desc: "Beef patty, bacon, cheese, avocado, jalapeño", price: "49.9k"},
    {id: "burger-elf", name: "Elven Delight", desc: "Churrasco, tomatoes, mashed avocado, mayo", price: "49.9k"},
    {id: "burger-dwarf", name: "Dwarven Feast", desc: "Churrasco, mozzarella, tomatoes, olives, mayo", price: "49.9k"},
    {id: "burger-gollum", name: "Gollum's Catch", desc: "Beer-battered cod, tartar sauce", price: "54.9k"},
    {id: "burger-mordor-steak", name: "Mordor Steak", desc: "Chopped beef, no bun", price: "54.9k"},
    {id: "burger-eorlingas", name: "Eorlingas Beef", desc: "Beef patty, french mustard, onions 3-ways", price: "54.9k"},
    {id: "burger-mirkwood", name: "Mirkwood Special", desc: "Reindeer patty, cheese, lingonberry jam", price: "59.9k"},
    {id: "burger-sauron", name: "Sauron's Delight", desc: "16oz wagyu beef, cheese, salt", price: "59.9k"},
    {id: "burger-samwise", name: "Samwise's Veggie", desc: "Deep fried potato, spicy chutney, chillies, onion", price: "39.9k"},
    {id: "burger-boromir", name: "Boromir's Special", desc: "Beef patty, green chutney, grilled onions, tomatoes", price: "39.9k"},
    {id: "burger-rivendell", name: "Rivendell Delight", desc: "Beef patty wrapped in fried egg", price: "39.9k"},
    {id: "burger-legolas", name: "Legolas Teriyaki", desc: "Chicken, teriyaki sauce, lettuce, tomatoes", price: "59.9k"},
    {id: "burger-frodo", name: "Frodo's Special", desc: "Organic crumbled mushroom, gruyere, lettuce, tomatoes, aioli", price: "54.9k"},
    {id: "burger-aragorn", name: "Aragorn's Feast", desc: "Beef patty, beetroot, fried egg, bacon", price: "54.9k"},
]
  
export const sides = [
    {id: "sides-shire-fries", name: "Shire Fries", desc: "Thick or thin", price: "19.9k"},
    {id: "sides-gondor", name: "Gondorian Poutine", desc: "Canadian fries, gravy, cheese", price: "22.9k"},
    {id: "sides-rohan", name: "Rohan's Mac n Cheese", desc: "Maccaroni, béchamel sauce, gruyere, cheddar, emmental", price: "24.9k"},
    {id: "sides-hobbit", name: "Hobbit's Mushy Peas", desc: "Peas mushed, mint", price: "19.9k"},
    {id: "sides-shire-dressed-fries", name: "Shire Dressed Fries", desc: "Thick fries, cheese sauce, chilli beef", price: "22.9k"},
    {id: "sides-bree", name: "Bree's Patatas Bravas", desc: "Deep-fried potato cubes, spicy tomato sauce", price: "20.9k"},
    {id: "sides-lorien", name: "Lothlórien Hummus + Pita", desc: "Mashed chickpeas, tahini, olive oil, lemon", price: "21.9k"},
    {id: "sides-rohan-rice", name: "Rohan's Spicy Rice", desc: "Long-grain rice, onion, peppers, Nandos spice blend", price: "21.9k"},
    {id: "sides-isengard", name: "Isengard Chizza", desc: "Deep-fried chicken pizza", price: "25.9k"},
    {id: "sides-gondor-spaghetti", name: "Gondorian Spaghetti", desc: "Spaghetti, sweet tomato sauce", price: "20.9k"},
    {id: "sides-rohan-double", name: "Rohan's Double Down", desc: "Sausage wrapped in deep-fried chicken", price: "21.9k"},
    {id: "sides-rivendell-toast", name: "Rivendell Kaya Toast", desc: "Kaya jam, butter", price: "20.9k"},
    {id: "sides-rivendell-okazu", name: "Rivendell Okazu", desc: "Gohan, misoshiru, umeboshi, tsukemono, natto", price: "25.9k"},
    {id: "sides-rohan-banchan", name: "Rohan's Banchan", desc: "Bap, gamja-tang, kimchi, namul, bokkeum, danmuji", price: "26.9k"},
]
  
export const drinks = [
    {id: "drinks-ale", name: "Ale of the Shire", desc: "Free flow ale", price: "19.9k"},
    {id: "drinks-gondor", name: "Gondorian Guinness", desc: "Irish dry stout", price: "33.9k"},
    {id: "drinks-rohan", name: "Rohan IPA", desc: "Hoppy, bitter, juicy", price: "34.9k"},
    {id: "drinks-rohan-pilsner", name: "Pilsner of Rohan", desc: "Golden, nice body, good head", price: "33.9k"},
    {id: "drinks-rivendell", name: "Rivendell's Kirin Ichiban", desc: "First press, crisp, refreshing", price: "34.9k"},
    {id: "drinks-gondor-sangria", name: "Gondorian Sangria", desc: "Garnacha, sweet citrus fruits, chilled", price: "33.9k"},
    {id: "drinks-rivendell-campari", name: "Rivendell Spritz", desc: "Campari, prosecco, soda water", price: "36.9k"},
    {id: "drinks-rohan-pisco", name: "Pisco of Rohan", desc: "Pisco, egg white, bitters, lime juice", price: "36.9k"},
    {id: "drinks-rivendell-caipirinha", name: "Rivendell Caipirinha", desc: "Cachaça, syrup, fresh lime", price: "36.9k"},
    {id: "drinks-elf-sake", name: "Elven Sake", desc: "Aged rice wine, served hot or cold", price: "38.9k"},
    {id: "drinks-rohan-poktanju", name: "Rohan's Poktanju", desc: "Beer, soju", price: "33.9k"},
]
  
export const dessert = [
    {id: "dessert-shire-pie", name: "Shire Apple Pie", desc: "Flaky crust, pink lady, whipped cream, vanilla ice-cream", price: "33.9k"},
    {id: "dessert-rohan-picarones", name: "Rohan Picarones", desc: "Sweet potato & squash doughnut, anise seed, chancaca syrup", price: "29.9k"},
    {id: "dessert-gondor-pastelitos", name: "Gondorian Pastelitos", desc: "Flaky puff pastry, sweet potato filling, syrup", price: "29.9k"},
    {id: "dessert-gondor-banoffee", name: "Gondorian Banoffee Pie", desc: "Digestives crust, bananas, toffee, whipped cream", price: "35.9k"},
    {id: "dessert-rivendell-macaron", name: "Elven Macaron", desc: "Almond meringue cookie, ganache", price: "35.9k"},
    {id: "dessert-rivendell-cremebrulee", name: "Crème Brulée of Rivendell", desc: "Creamy custard, browned caramel", price: "33.9k"},
    {id: "dessert-hobbit-waffles", name: "Hobbit's Belgian Waffles", desc: "Warm waffles, nutella, powdered sugar", price: "34.9k"},
    {id: "dessert-rohan-gelato", name: "Rohan Gelato", desc: "Raspberry, pistachio, rum, chocolate", price: "29.9k"},
    {id: "dessert-rohan-baklava", name: "Baklava of Rohan", desc: "Phyllo pastry, honey, pistachio, walnut, hazelnut", price: "37.9k"},
    {id: "dessert-gondor-koeksisters", name: "Gondorian Koeksisters", desc: "Deep-fried dough rolls, cold sugar syrup", price: "29.9k"},
    {id: "dessert-rivendell-mochi", name: "Mochi of Rivendell", desc: "Glutinous rice ball, sweet filling", price: "39.9k"},
    {id: "dessert-shire-lamingtons", name: "Shire Lamingtons", desc: "Sponge cake, chocolate coating, coconut sprinkles", price: "32.9k"},
]  